### ISSUE TITLE
Synthesis microarchitecture automatically

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/nitta#157]
After: #154 #155 #156

We need:
- [ ] design metrics to make a decision about the microarchitecture and write a meaningful estimate function
- [ ] add CLI  argument: `--auto-microarchitecture`
  - if `--microarchitecture` is not presented, start with empty BusNetwork
  - if `--microarchitecture` is presented, start with the specified microarchitecture and auto-modify it
  - if `--auto-microarchitecture` is not presented - avoid microarchitecture synthesis.
- [ ] debug it on example algorithms and add tests.

**Comment by BasicEC** [comment]
@ryukzak

I propose to rename `--auto-microarchitecture` to `--auto-uarch`.
Also, based on the implementation that was made in #195 , I propose the following behavior:
1. `--auto-uarch` is presented with `--uarch` - then `--auto-uarch` is ignored (because there should be prototypes specified in config file)
2. `--auto-uarch` is presented and `--uarch` is not - then we start with BusNetwork without PUs and all default prototypes.
  (I guess SPI also should be presented in BusNetwork because SPI prototypes disabled because of #194
4.`--auto-uarch` is not presented - avoid microarchitecture synthesis, start with default BusNetwork.

Therefore, we need to additionally add the loading of the list of prototypes from the configuration file.
